# Parameters
Lx = 1.0 # Longitud del dominio
Ly = 1.0 # Longitud del dominio
T = 500.0  # Tiempo total de simulación
Nx = 256  # Número de puntos de la cuadrícula
Ny = 256  # Número de puntos de la cuadrícula
dt = 1e-3
Nt = int(T/dt)  # Número de pasos de tiempo
nu = 1.0/40.0
print_freq = 10
save_freq = 50
fields_freq = 50 
rkord = 2 # order of RK
T_guess = 5.5
t_guess = 250
N_newt = 5
N_gmres = 10
tol_newt = 1e-5
tol_gmres = 1e-5